### ISSUE TITLE
null being mapped to "\"null\""

### ISSUE THREAD

**Issue by jwboardman** [Flight-School/AnyCodable#30] opened 2020-02-06 20:37 UTC
This mapping is resulting in the string "null" to be shown in our app as if it is a legal value, and forcing us to do a regex to replace "\\"null\\"" with "null" in the resulting JSON before sending it on to our app, so in JSON you would see
  "value",null,"value"
for example instead of
  "value","null","value2"

Could null please be mapped to just null please?

**Comment by mattt** [comment] 2020-02-06 21:59
Duplicate of #29.

**Closed by mattt** 2020-02-06 21:59 UTC
